Repository Growth-and-Start/TokenUs, pull requests merged in 2024-12, with the labels that each got.

#5 feat: Minting Video NFT #2
  .gitignore
  contracts/VideoNFT.sol
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
  test/VideoNFT.test.js
  truffle-config.js
Labels: :memo: docs, :new: feature

#6 Modify VideoNFT code
  contracts/VideoNFT.sol
Labels: :memo: docs

#7 feat: MINT ERC20
  contracts/Channel.sol
  contracts/Swap.sol
  contracts/Tokenus.sol
  migrations/2_deploy_contracts.js
  test/Swap.test.js
Labels: :new: feature

#9 feat: VideoNFT Trading
  README.md
  contracts/VideoNFTMarketplace.sol
  migrations/2_deploy_contracts.js
  test/VideoNFTMarketplace.test.js
Labels: :new: feature
